name: ci_cd_pipeline_development.yml
on:
  schedule:
    - cron: '30 13 * * 1,2,3,4,5'
  push:
    # Sequence of patterns matched against refs/heads
    branches-ignore:    
      - 'nab/octocat'
      - 'releases/**-alpha'
    # Sequence of patterns matched against refs/tags
    tags-ignore:        
      - v2
      - v1.*
  workflow_dispatch:

env:
  ## Cloudhub Properties
  CLOUDHUB_USERNAME: ${{ secrets.CLOUDHUB_USERNAME }}
  CLOUDHUB_PASSWORD: ${{ secrets.CLOUDHUB_PASSWORD }}
  CLOUDHUB_WORKERS: 2
  CLOUDHUB_WORKER_TYPE: MICRO
  CLOUDHUB_REGION: us-east-01  

  ## API specific 
  HTTP_PRIVATE_PORT: 8091  

jobs:
  build_deploy_dev-01:
    uses: ./.github/workflows/build_deploy_reusable.yml
    with:
      CLOUDHUB_USERNAME: ${{ env.CLOUDHUB_USERNAME }}
      CLOUDHUB_PASSWORD: ${{ env.CLOUDHUB_PASSWORD }}
      CLOUDHUB_ENVIRONMENT: "dev-01"
      GITHUB_ENVIRONMENT: "dev"      
      CLOUDHUB_WORKERS: ${{ env.CLOUDHUB_WORKERS }}
      CLOUDHUB_WORKER_TYPE: ${{ env.CLOUDHUB_WORKER_TYPE }}      
      CLOUDHUB_REGION: ${{ env.CLOUDHUB_REGION }}     
      HTTP_PRIVATE_PORT: ${{ env.HTTP_PRIVATE_PORT }}   
    secrets:
      CLOUDHUB_PASSWORD : ${{ secrets.CLOUDHUB_PASSWORD }}


  build_deploy_dev-02:
    uses: ./.github/workflows/build_deploy_reusable.yml
    with:
      CLOUDHUB_USERNAME: ${{ env.CLOUDHUB_USERNAME }}
      CLOUDHUB_PASSWORD: ${{ env.CLOUDHUB_PASSWORD }}
      CLOUDHUB_ENVIRONMENT: "dev-02"
      GITHUB_ENVIRONMENT: "dev"      
      CLOUDHUB_WORKERS: ${{ env.CLOUDHUB_WORKERS }}
      CLOUDHUB_WORKER_TYPE: ${{ env.CLOUDHUB_WORKER_TYPE }}      
      CLOUDHUB_REGION: ${{ env.CLOUDHUB_REGION }}     
      HTTP_PRIVATE_PORT: ${{ env.HTTP_PRIVATE_PORT }}   
    secrets:
      CLOUDHUB_PASSWORD : ${{ secrets.CLOUDHUB_PASSWORD }}
