name: ci_cd_pipeline_release_stage_prod.yml

# Run on new release creation or when manually triggered
on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Where to release (staging or prod)?'     
        required: true
        default: 'staging'
env:
  ## Cloudhub Properties
  CLOUDHUB_USERNAME: ${{ secrets.CLOUDHUB_USERNAME }}
  CLOUDHUB_PASSWORD: ${{ secrets.CLOUDHUB_PASSWORD }}
  CLOUDHUB_WORKERS: 2
  CLOUDHUB_WORKER_TYPE: MICRO
  CLOUDHUB_REGION: us-east-01  

  ## API specific 
  HTTP_PRIVATE_PORT: 8091  

jobs:
  staging:
    uses: ./.github/workflows/build_deploy_reusable.yml
    with:
      CLOUDHUB_USERNAME: ${{ env.CLOUDHUB_USERNAME }}
      CLOUDHUB_PASSWORD: ${{ env.CLOUDHUB_PASSWORD }}
      CLOUDHUB_ENVIRONMENT: "uat-01"
      GITHUB_ENVIRONMENT: "staging"      
      CLOUDHUB_WORKERS: ${{ env.CLOUDHUB_WORKERS }}
      CLOUDHUB_WORKER_TYPE: ${{ env.CLOUDHUB_WORKER_TYPE }}      
      CLOUDHUB_REGION: ${{ env.CLOUDHUB_REGION }}     
      HTTP_PRIVATE_PORT: ${{ env.HTTP_PRIVATE_PORT }}   
    secrets:
      CLOUDHUB_PASSWORD : ${{ secrets.CLOUDHUB_PASSWORD }}

  prod:
    if: github.event.inputs.releaseType == 'prod'  
    uses: ./.github/workflows/build_deploy_reusable.yml
    with:
      CLOUDHUB_USERNAME: ${{ env.CLOUDHUB_USERNAME }}
      CLOUDHUB_PASSWORD: ${{ env.CLOUDHUB_PASSWORD }}
      CLOUDHUB_ENVIRONMENT: "prod-01"
      GITHUB_ENVIRONMENT: "prod"      
      CLOUDHUB_WORKERS: ${{ env.CLOUDHUB_WORKERS }}
      CLOUDHUB_WORKER_TYPE: ${{ env.CLOUDHUB_WORKER_TYPE }}      
      CLOUDHUB_REGION: ${{ env.CLOUDHUB_REGION }}     
      HTTP_PRIVATE_PORT: ${{ env.HTTP_PRIVATE_PORT }}   
    secrets:
      CLOUDHUB_PASSWORD : ${{ secrets.CLOUDHUB_PASSWORD }}
